POST http://localhost:3000/api/pedidos
Content-Type: application/json

{
    "itens": [
        {
            "produto_id": 1,
            "quantidade": 2
        },
        {
            "produto_id": 2,
            "quantidade": 1
        },
        {
            "produto_id": 4,
            "quantidade": 1
        }
    ]
}

###

GET http://localhost:3000/api/pedidos

###

DELETE http://localhost:3000/api/pedidos/8

###

PATCH  http://localhost:3000/api/pedidos/2
Content-Type: application/json

{
    "status": "finalizado"
}

###

PUT http://localhost:3000/api/pedidos/10
Content-Type: application/json

{
    "itens": [
        {
            "produto_id": 1,
            "quantidade": 3
        },
        {
            "produto_id": 2,
            "quantidade": 1
        },
        {
            "produto_id": 4,
            "quantidade": 4
        }
    ]
}